### ISSUE TITLE
Review JavaDoc

### ISSUE THREAD

**Issue by marvec** [PerfCake/PerfCake#150]
Review the JavaDoc, unify its style and language throughout the complete source code.

**Comment by marvec** [comment]
Warnings are now removed, a thorough review needs to be done now.

**Comment by marvec** [comment]
Great job!

**Comment by tborcin** [comment]
JmsSender
402: Is JMS message persisted. (period instead of question mark)

HttpSender
59: The URL where the HTTP request is send. (shouldn't be "sent"?)
353: method missing javadoc

AbstractMessageGenerator
107: Semaphore that will be release upon completion of the sender task. ("released" ?)
226: missing javadoc?

ConstantSpeedMessageGenerator
84 and 88: missing javadoc

DefaultMessageGenerator
61, 72 and 83: It the same amount of threads keeps running for this period, they are forcefully stopped.
132: When it was not possible to place another task because the queue was empty (missing period)

MessageGenerator
101: {@link org.perfcake.validation.ValidationManager} to be used.s

RampUpDownGenerator
84: An final number of threads.
