### ISSUE TITLE
StackOverflowError when using big messages with templates

### ISSUE THREAD

**Issue by FilipB** [PerfCake/PerfCake#260]
When using big messages with templates e.g.
[{"id":"gaugeID1","data":[{"timestamp": "@{CurrentTimestamp}", "value": 10.12}]},
{"id":"gaugeID2","data":[{"timestamp": "@{CurrentTimestamp}", "value": 10.12}]},
{"id":"gaugeID3","data":[{"timestamp": "@{CurrentTimestamp}", "value": 10.12}]},
.
.
{"id":"gaugeID1000","data":[{"timestamp": "@{CurrentTimestamp}", "value": 10.12}]}
]
StackOverflowError is thrown when parsing the template.
Full json, test scenario and exception is attached. (attached as txt because of github filter)

[gauges-post-test.txt](https://github.com/PerfCake/PerfCake/files/32007/gauges-post-test.txt)
[test.txt](https://github.com/PerfCake/PerfCake/files/32013/test.txt)
[exception.txt](https://github.com/PerfCake/PerfCake/files/32018/exception.txt)

**Comment by marvec** [comment]
Hello Filip and thanks for reporting! 
I did some analysis and found the root cause - for the templates to work really fast, they are converted to java classes and compiled. The problem is that the template has too large method - the resulting class bytecode exceeds Java limits. I can imagine implementing a backup code that would be much slower, but capable of handling such large templates.
For now, you can use several workarounds:
1) send more smaller messages
2) send more messages per single sender cycle
3) prepare a set of separate message files, each different, and you could use a sequence to generate message file name in the scenario (see https://github.com/PerfCake/PerfCake/blob/v5.1/perfcake/src/main/java/org/perfcake/message/sequence/FileLinesSequence.java)
