### ISSUE TITLE
JavaDoc and User/Dev guide URLs returning a 404 Not Found

### ISSUE THREAD

**Issue by jyotheeshwar** [PerfCake/PerfCake#390]
https://javadoc.perfcake.org/
https://www.perfcake.org/docs/user-guide/ug.introduction.first-performance.test.html
https://www.perfcake.org/docs/developers-guide/perfcake-developers-guide.html
and PDF links are returning a 404.

**Comment by marvec** [comment]
Hello, the site was broken because a change to our infrastructure. The guides are back online. For now, our plan was not to host javadoc anymore because we are not able to do that easily with GitHub pages. However, if this is anything you really appreciate, we will seek for a solution. The URL will change definitely.

**Comment by marvec** [comment]
Also, please note that we do not use HTTPS anymore. Use HTTP instead (GitHub pages do not support that with a custom domain).

**Comment by jyotheeshwar** [comment]
Hi, no this is great! I haven't used the javadocs too much, so this is perfect. Thanks! Should I leave this issue open for you to close, or should I close it myself?

**Comment by pmacik** [comment]
Hi, the javadoc is back and the URL has moved to [http://perfcake.org/javadoc](http://perfcake.org/javadoc).
